###Get All Phones
GET http://localhost:8080/api/phones
Accept: application/json

###Find One Phone Exist
GET http://localhost:8080/api/phones/1

###Find One Phone Non-exist
GET http://localhost:8080/api/phones/99999999

###Get All Phones By Page
GET http://localhost:8080/api/phones?page=1

###Get All Phones By Page And Size
GET http://localhost:8080/api/phones?page=0&size=2

###Get All Phones By Page, Size, Sort
GET http://localhost:8080/api/phones?page=0&size=5&sort=brand

###Create new Phone with null id
POST http://localhost:8080/api/phones/create
Content-Type: application/json

{
  "brand": "nokia",
  "model": "nokia 6610",
  "price": 10000000
}

###Create new Phone with exist id
POST http://localhost:8080/api/phones/create
Content-Type: application/json

{
  "id": 1,
  "brand": "nokia",
  "model": "nokia 6610",
  "price": 10000000
}

###Update Exist Phone
PUT http://localhost:8080/api/phones/update
Content-Type: application/json

{
  "id": 1,
  "brand": "Cục gạch",
  "model": "Ném chó chó chết",
  "price": 0
}

###Update Phone with null id
PUT http://localhost:8080/api/phones/update
Content-Type: application/json

{
  "brand": "Cục gạch",
  "model": "Ném chó chó chết",
  "price": 0
}

###Update Phone with non exist id
PUT http://localhost:8080/api/phones/update
Content-Type: application/json

{
  "id" : 9999,
  "brand": "Cục gạch",
  "model": "Ném chó chó chết",
  "price": 0
}

###Delete Exist Phone
DELETE http://localhost:8080/api/phones/2/delete
Content-Type: application/json

###Delete Phone with null id
DELETE http://localhost:8080/api/phones/delete/
Content-Type: application/json

###Delete Phone with non exist id
DELETE http://localhost:8080/api/phones/delete/1
Content-Type: application/json